spring.application.name=telegram-agent-ui-phase3

telegram.bot.name=${TELEGRAM_BOT_NAME:PorkinsBot}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:REEMPLAZAR_CON_TOKEN_REAL}

agent.ai.enabled=${AGENT_AI_ENABLED:true}
agent.ai.base-url=${AGENT_AI_BASE_URL:https://generativelanguage.googleapis.com/v1beta}
agent.ai.api-key=${AGENT_AI_API_KEY:REEMPLAZAR_CON_API_KEY_REAL}
agent.ai.model=${AGENT_AI_MODEL:gemini-2.0-flash}

logging.level.root=INFO
logging.level.com.oraclebot=DEBUG
